language: "node_js"

node_js:
    - "0.10"
    - "0.12"
    - "v4"
    - "v5"
    - "v6"

sudo: false

notifications:
  email:
    on_failure: change

before_install:
  - npm install -g npm

script:
  - xvfb-run -a npm test
  - npm run test-coverage
